# Site settings
baseurl = "https://beta.axelsegebrecht.com/"
languageCode = "en-us"
title = "Axel Segebrecht (Digital Project Manager)"
theme = "hugo-highlights-theme"

# Enter your tracking code to enable Google analytics
googleAnalytics = ""

[params]

  # You can use Markdown for urls [text](//domain.tld/source)
  #
  # All icons using Fontawesom's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
  # for more icons.

  # To provide more meta data for search engings feel free to add a few informations.
  # This lines will be inserted as meta tags.
  name = "Axel Segebrecht"
  description = "Digital Project Manager"

  # For a static site it's not possible to provide a contact form. The contact form uses
  # www.formspree.io as a proxy. The form makes a Post request to their servers to send an email
  # Visitors can send up to a 1000 emails each month
  #
  # How to setup formspree
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email to yourself to confirm your account
  # - click the confirmation link in the email from www.formspree.io
  # - That's all. Enjoy mailing!
  email = "axel@segebrecht.com"

  # If this param is set to true, every section gets an own background image (located at static/images)
  # to change the image you could use the param picture on every section.
  # If it's disabled you could change the background to overwrite the bg.png and overlay.png to set the background.
  backgroundpersection = true

  # Hero Section
  [params.hero]
    title = "Axel Segebrecht"
    description = "Digital Project Manager"
    buttontext = "explore"

  # about section
  [params.about]
    enable = true
    title = "Who am I"
    description = "I am Axel, a German-born project manager and advisor on digital projects based in Bletchley, Milton Keynes (UK). Speaking both English and German fluently, I can help crossing cultural boundaries and bringing project teams across together."
    buttontext = "next"
    # the picture is storead at static/images/
    picture = "IMG_3610.jpg"

  # skill section
  [params.skill_list]
    enable = true
    title = "What I do"
    description = "People have been relying on my versatility and detailed comprehension of digital technology to successfully deliver - and sometimes rescue - digital, marketing and IT-related projects."

    buttontext = "next"
    # the picture is storead at static/images/
    picture = "benjamin-child-17946.jpg"

    [[params.skills]]
      icon = "fa-plus-circle"
      title = "Rescuing"
      subtitle = "projects at risk of failure"

    [[params.skills]]
      icon = "fa-lock"
      title = "Protecting"
      subtitle = "business value certainty"

    [[params.skills]]
      icon = "fa-reorder"
      title = "Aligning"
      subtitle = "delivery with strategy"

    [[params.skills]]
      icon = "fa-bank"
      title = "Governing"
      subtitle = "effectively controlling"

  # infos section
  [params.infos]
    enable = true
    title = "Getting things done"
    description = "My approach utilises agile or scrum methodologies and has the business' needs at heart. I customise a unique approach for each case; helping to deliver change with certainty. My value proposition to you is simple: I can help get your digital project delivering quickly, whilst balancing speed with risk and managing complex stakeholder situations effectively"
    # the picture is storead at static/images/
    picture = "paul-smith-192401.jpg"

  # footer section
  # this section includes
  #
  # - the contact form
  # - social icons
  #
  # It's possible to disable the whole footer or disable only social icons or contact form

  [params.footer]
    enable = true
    title = "Get in Touch"
    subtitle = "To explore how I can help get things done for you, **call or message me on +447794132161** for an unconditional conversation. I also use [Signal](https://whispersystems.org/), [Wire](https://www.wire.com/), [Telegram](https://www.google.co.uk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjz1orirdTSAhUQahoKHfwcDMsQFggcMAA&url=https%3A%2F%2Ftelegram.org%2F&usg=AFQjCNFKVwj_TnUWOxeJw2Vdu1NhzxihzA) and iMessage to keep communications secure."

    # contact form
    [params.footer.contact]
      enable = true

    [params.footer.contact.form]
      name = "Name"
      email = "Your Email"
      message = "Your Message"
      buttontext = "send message"

    # social icons
    [params.footer.social_list]
      enable = true

      [[params.footer.social]]
        title = "Twitter"
        icon = "fa-twitter"
        link = "https://twitter.com/axelsegebrecht"

      [[params.footer.social]]
        title = "Github"
        icon = "fa-github"
        link = "https://github.com/axelsegebrecht"

      [[params.footer.social]]
        title = "Email"
        icon = "fa-envelope"
        link = "axel@segebrecht.com"

    # copyright
    #[params.footer.copyright.notice]

      [[params.footer.copyright.notice]]
        text = "© Axel Segebrecht (be braver Ltd)"

      [[params.footer.copyright.notice]]
        text = "Design: [HTML5UP](//html5up.net)"

      [[params.footer.copyright.notice]]
        text = "Images: by be braver Ltd and [Unsplash](//unsplash.com/)"
